-- Run once as ACCOUNTADMIN to add claim-list fields needed for the
-- Snowflake-backed frontend table.
USE ROLE ACCOUNTADMIN;
USE DATABASE XANO_DEMO;
USE SCHEMA CLAIMS_DEMO;

ALTER TABLE CLAIM_POLICY_CONTEXT ADD COLUMN IF NOT EXISTS AMOUNT_REQUESTED NUMBER(12,2);
ALTER TABLE CLAIM_POLICY_CONTEXT ADD COLUMN IF NOT EXISTS CLAIM_STATUS STRING;
ALTER TABLE CLAIM_POLICY_CONTEXT ADD COLUMN IF NOT EXISTS CLAIM_PRIORITY STRING;
ALTER TABLE CLAIM_POLICY_CONTEXT ADD COLUMN IF NOT EXISTS ASSIGNED_QUEUE STRING;
ALTER TABLE CLAIM_POLICY_CONTEXT ADD COLUMN IF NOT EXISTS SUMMARY STRING;
ALTER TABLE CLAIM_POLICY_CONTEXT ADD COLUMN IF NOT EXISTS OPENED_AT TIMESTAMP_NTZ;
