-- Run once as ACCOUNTADMIN so the demo key-pair user can seed/update demo data.
USE ROLE ACCOUNTADMIN;
GRANT INSERT, UPDATE, DELETE ON TABLE XANO_DEMO.CLAIMS_DEMO.CLAIM_POLICY_CONTEXT TO ROLE XANO_DEMO_ROLE;
GRANT INSERT, UPDATE, DELETE ON TABLE XANO_DEMO.CLAIMS_DEMO.CUSTOMER_CLAIM_HISTORY TO ROLE XANO_DEMO_ROLE;
