-- Northstar Claims Snowflake demo setup
-- Run this as a Snowflake admin user, then paste the generated connection
-- values into Xano's External Query Connection Wizard.

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS XANO_DEMO;
USE DATABASE XANO_DEMO;
CREATE SCHEMA IF NOT EXISTS CLAIMS_DEMO;
USE SCHEMA CLAIMS_DEMO;

CREATE ROLE IF NOT EXISTS XANO_DEMO_ROLE;

-- Replace the placeholder password before running.
CREATE USER IF NOT EXISTS XANO_DEMO_USER
  PASSWORD = 'ABCDEFG1234567!@#$%'
  DEFAULT_ROLE = XANO_DEMO_ROLE
  DEFAULT_WAREHOUSE = COMPUTE_WH
  DEFAULT_NAMESPACE = XANO_DEMO.CLAIMS_DEMO
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE XANO_DEMO_ROLE TO USER XANO_DEMO_USER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE XANO_DEMO_ROLE;
GRANT USAGE ON DATABASE XANO_DEMO TO ROLE XANO_DEMO_ROLE;
GRANT USAGE ON SCHEMA CLAIMS_DEMO TO ROLE XANO_DEMO_ROLE;

CREATE OR REPLACE TABLE CLAIM_POLICY_CONTEXT (
  CLAIM_ID NUMBER,
  CLAIM_NUMBER STRING,
  CUSTOMER_ID NUMBER,
  CUSTOMER_NAME STRING,
  CLAIM_TYPE STRING,
  POLICY_NUMBER STRING,
  POLICY_STATUS STRING,
  POLICY_AGE_MONTHS NUMBER,
  COVERAGE_TIER STRING,
  DEDUCTIBLE NUMBER,
  COVERAGE_VALID BOOLEAN,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CUSTOMER_CLAIM_HISTORY (
  CUSTOMER_ID NUMBER,
  PRIOR_CLAIM_COUNT NUMBER,
  PRIOR_CLAIM_TOTAL NUMBER(12, 2),
  FRAUD_FLAG BOOLEAN,
  LAST_CLAIM_AT TIMESTAMP_NTZ,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CLAIM_ESCALATION_AUDIT (
  EVENT_ID STRING DEFAULT UUID_STRING(),
  CLAIM_ID NUMBER,
  CLAIM_NUMBER STRING,
  ROUTE STRING,
  PRIORITY STRING,
  DECISION STRING,
  PAYLOAD VARIANT,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO CLAIM_POLICY_CONTEXT (
  CLAIM_ID,
  CLAIM_NUMBER,
  CUSTOMER_ID,
  CUSTOMER_NAME,
  CLAIM_TYPE,
  POLICY_NUMBER,
  POLICY_STATUS,
  POLICY_AGE_MONTHS,
  COVERAGE_TIER,
  DEDUCTIBLE,
  COVERAGE_VALID
) VALUES
  (99,  'CLM-2026-00099', 104, 'Maya Chen',     'property',  'POL-PROP-0099', 'active', 28, 'homeowners_plus', 500, TRUE),
  (107, 'CLM-2026-00107', 114, 'Priya Shah',    'property',  'POL-PROP-0107', 'active', 18, 'homeowners_plus', 500, TRUE),
  (101, 'CLM-2026-00101', 106, 'Andre Wilson',  'liability', 'POL-LIAB-0101', 'active', 42, 'umbrella',        1000, TRUE),
  (116, 'CLM-2026-00116', 122, 'Jordan Miles',  'auto',      'POL-AUTO-0116', 'active', 30, 'comprehensive',  750, TRUE);

INSERT INTO CUSTOMER_CLAIM_HISTORY (
  CUSTOMER_ID,
  PRIOR_CLAIM_COUNT,
  PRIOR_CLAIM_TOTAL,
  FRAUD_FLAG,
  LAST_CLAIM_AT
) VALUES
  (104, 2, 12400.00, FALSE, '2025-11-18 15:30:00'),
  (114, 1,  5200.00, FALSE, '2025-08-04 09:15:00'),
  (106, 3, 31000.00, TRUE,  '2026-01-12 12:00:00'),
  (122, 0,     0.00, FALSE, NULL);

GRANT SELECT ON ALL TABLES IN SCHEMA XANO_DEMO.CLAIMS_DEMO TO ROLE XANO_DEMO_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA XANO_DEMO.CLAIMS_DEMO TO ROLE XANO_DEMO_ROLE;
GRANT INSERT ON TABLE XANO_DEMO.CLAIMS_DEMO.CLAIM_ESCALATION_AUDIT TO ROLE XANO_DEMO_ROLE;

-- Xano External Query Connection Wizard values:
-- Account: VJSKWGT-CO19189
-- Database name: XANO_DEMO
-- Username: XANO_DEMO_USER
-- Port: 443
-- Schema: CLAIMS_DEMO
-- Warehouse: COMPUTE_WH
-- Connection string:
-- snowflake://XANO_DEMO_USER:<password>@VJSKWGT-CO19189:443/XANO_DEMO/CLAIMS_DEMO?warehouse=COMPUTE_WH&role=XANO_DEMO_ROLE
